import os
import sys
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse, HTMLResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

# Add current directory to path to prevent import issues
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

# Automatically run ingestion on startup if database does not exist
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(os.path.dirname(BASE_DIR), "data")
CHROMA_DIR = os.path.join(DATA_DIR, "chroma_db")

if not os.path.exists(CHROMA_DIR):
    print("[*] ChromaDB database not found. Running ingestion pipeline...")
    try:
        from ingestion import ingest_documents
        ingest_documents()
    except ImportError:
        from backend.ingestion import ingest_documents
        ingest_documents()

try:
    from retrieval import stream_rag
except ImportError as e:
    # Fallback if run from parent folder
    from backend.retrieval import stream_rag

# Initialize FastAPI App
app = FastAPI(
    title="AutoDiag-AI Backend",
    description="FastAPI service for AutoDiag-AI chatbot RAG pipeline",
    version="1.0.0"
)

# Configure CORS Middleware
# Allows connection from typical frontend dev servers (Vite: 5173, Create React App: 3000) or any source
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # In production, replace with specific frontend URLs
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class ChatRequest(BaseModel):
    message: str

@app.get("/api/health")
async def health_check():
    """Health check endpoint to ensure API service is up."""
    return {"status": "healthy", "service": "AutoDiag-AI Backend"}
@app.post("/api/chat")
async def chat_endpoint(request: ChatRequest):
    """
    Receives chat messages from user and streams response from Gemini RAG pipeline.
    Uses Server-Sent Events (SSE) streaming.
    """
    if not request.message.strip():
        raise HTTPException(status_code=400, detail="Message cannot be empty")
        
    print(f"[*] Received chat request: {request.message}")
    
    return StreamingResponse(
        stream_rag(request.message),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no"  # Prevents Nginx buffering streams
        }
    )
# Static Files serving configuration

# Locate frontend folder
FRONTEND_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "frontend")
DIST_DIR = os.path.join(FRONTEND_DIR, "dist")

if os.path.exists(DIST_DIR):
    # Mount assets folder generated by Vite
    assets_path = os.path.join(DIST_DIR, "assets")
    if os.path.exists(assets_path):
        app.mount("/assets", StaticFiles(directory=assets_path), name="assets")
    # Keep /static mount for any backend assets if needed
    app.mount("/static", StaticFiles(directory=FRONTEND_DIR), name="static")
elif os.path.exists(FRONTEND_DIR):
    app.mount("/static", StaticFiles(directory=FRONTEND_DIR), name="static")

@app.get("/", response_class=HTMLResponse)
async def serve_index():
    """Serves the test frontend integration page."""
    # Check if built Vite output exists first
    dist_index = os.path.join(DIST_DIR, "index.html")
    if os.path.exists(dist_index):
        with open(dist_index, "r", encoding="utf-8") as f:
            return f.read()

    # Fallback to dev/raw index.html
    index_path = os.path.join(FRONTEND_DIR, "index.html")
    if os.path.exists(index_path):
        with open(index_path, "r", encoding="utf-8") as f:
            return f.read()
    return "<h3>AutoDiag-AI Backend is running successfully.</h3><p>Static frontend index.html not found in frontend directory.</p>"


if __name__ == "__main__":
    import uvicorn
    # Read port from environment or default to 8000
    port = int(os.getenv("PORT", 8000))
    print(f"[*] Starting AutoDiag-AI server on port {port}...")
    uvicorn.run("main:app", host="0.0.0.0", port=port, reload=True)
